spring.application.name=gateway

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.client.registry-fetch-interval-seconds=5

server.port=8081