spring.application.name=pagamentos-ms

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/pagamentos-db

# Eureka
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

server.port=0

# Circuit Breaker
# Configuracao padrao para todos os circuit breakers
resilience4j.circuitbreaker.configs.default.slidingWindowSize: 3
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls: 2
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState: 25s
resilience4j.circuitbreaker.configs.default.record-exceptions=java.lang.Exception
resilience4j.circuitbreaker.configs.default.ignore-exceptions=com.martinsdev.pagamentos.infra.exception.InvalidOperationException,com.martinsdev.pagamentos.infra.exception.ResourceNotFoundException
spring.cloud.openfeign.client.config.default.retryer=feign.Retryer$Default

# Cada instancia herda o padrao
resilience4j.circuitbreaker.instances.criarPagamento.baseConfig=default

# FeingClient - puxando a vari�vel de ambiente l� do PagamentosServiceStack
pedidos.ms.url=${PEDIDOS_MS_URL:}

#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
#Publish Confirms
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true